# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVvfjc34wTCujlGNF46puZcHmpHJrtY5
"""

streamlit
pandas
matplotlib